### ISSUE TITLE
Eventually remove animal-sniffer plugin

### ISSUE THREAD

**Issue by rhusar** [arquillian/arquillian-extension-warp#199]
No longer needed post JDK 8.

**Comment by WolfgangHG** [comment]
Is there anything to be done during the build process (comment from issue 62: "The javac tool has been extended with the release flag in Java 9, which does the signature checking")? I assume not, as we declare a java version by maven properties?

**Comment by rhusar** [comment]
> Is there anything to be done during the build process (comment from issue 62: "The javac tool has been extended with the release flag in Java 9, which does the signature checking")? I assume not, as we declare a java version by maven properties?

Lets revisit after jboss-parent upgrade, that needs more work and I haven't gotten to it and it might fix some things.
