### ISSUE TITLE
Unignore 2 tests ignored with move to JDK 11

### ISSUE THREAD

**Issue by rhusar** [arquillian/arquillian-extension-warp#203]
Basically revert this commit - https://github.com/arquillian/arquillian-extension-warp/pull/201/commits/f0a79e34f7cb6ad0056e4c0e2fe4761709832f95

**Comment by WolfgangHG** [comment]
Both tests contain a `org.jboss.arquillian.warp.Inspection` (snippet from `org.jboss.arquillian.warp.jsf.ftest.BasicJsfTest`), and injection does not seem to happen:

```java
            .inspect(new Inspection() {
                         private static final long serialVersionUID = 1L;

                         @Inject
                         CdiBean myBean;

                         @AfterPhase(RENDER_RESPONSE)
                         public void initial_state_havent_changed_yet() {
                             assertEquals("John", myBean.getName());
                         }
                     }
            );
```

It works for me when switching back to the previous version in root "pom.xml":
```
<version.wildfly.arquillian.container>3.0.1.Final</version.wildfly.arquillian.container>
```

4.0.1.Final also works.

According to https://github.com/wildfly/wildfly-arquillian:  "Versions 5.0 for for Jakarta EE 10 and work with WildFly 27 and higher and JBoss EAP 8.0 and higher".

So we were to fast by updating it :-)? See also #141

**Comment by rhusar** [comment]
Done, thanks @WolfgangHG !
