### ISSUE TITLE
Version 1.1.0.Final payload

### ISSUE THREAD

**Issue by rhusar** [arquillian/arquillian-extension-warp#213]
Payload

* This will be the last release for Java EE 8
* It is targeting WF 26 (and older EE 8-compliant)
* It will be based on JDK 11
* Project dependencies with be brought up to date, including arquillian-core 1.9

**Comment by rhusar** [comment]
@WolfgangHG Let's finalize the payload for 1.1.0.Final release. Is there something else that should be included that you are aware of? Once we finalize this release, I ll merge the EE 10 upgrade (I have already implemented this :P) and move to 2.0.

**Comment by rhusar** [comment]
There is a lot of issues in Jira that will need triage. Perhaps material for 2.x, since many of the issues will no longer be relevant. WDYT @WolfgangHG ?

**Comment by WolfgangHG** [comment]
I see not many todos for Java 11 - and if you are done with the JakartaEE10 migration, I am actually out of bussiness ;-).

I would like to get rid of the deprecation warnings, and Eclipse reports a bunch of unused imports, but that's all.

Some time ago I took a look at the JIRA issues, but they all are feature enhancements that are far off my knowledge. My aim was to keep this extension usable and alive - I still don't understand 99% of it ;-)

**Comment by WolfgangHG** [comment]
@rhusar  OK, I will keep it calm until you committed the JakartaEE10 fixes ;-)

**Comment by WolfgangHG** [comment]
> > I would like to get rid of the deprecation warnings, and Eclipse reports a bunch of unused imports, but that's all.
> 
> Please hold on until main moved to 2.x, since the jakarta migration is all work in the imports section.

The unused imports was an error by me - I had switched off JavaDoc validation in Eclipse, and those unused imports were all used in JavaDoc comments.

**Comment by rhusar** [comment]
> > > I would like to get rid of the deprecation warnings, and Eclipse reports a bunch of unused imports, but that's all.
> > 
> > 
> > Please hold on until main moved to 2.x, since the jakarta migration is all work in the imports section.
> 
> The unused imports was an error by me - I had switched off JavaDoc validation in Eclipse, and those unused imports were all used in JavaDoc comments.

I didn't see those either, thanks for confirming. Nevertheless, I don't like imports like that and just use FQCN in the Javadoc. If you agree please open an issue - but please PR after the EE 10 merge as that would conflict heavily.

**Comment by rhusar** [comment]
@WolfgangHG Also added arquillian-core 1.9.0 upgrade - https://github.com/arquillian/arquillian-extension-warp/pull/223 - I am not sure why this wasn't picked up by dependabot like it was previously..

**Comment by rhusar** [comment]
OK, brought up last 2 dependenies up to date manually - https://github.com/arquillian/arquillian-extension-warp/pull/225

@WolfgangHG Can you think of anything else for the 1.1.0.Final release before we move on to 2.0 and Jakarta EE 10?

**Comment by WolfgangHG** [comment]
@rhusar Nope, nothing on my list besides the deprecation warnings. But they can be resolved later.

**Comment by rhusar** [comment]
> @rhusar Nope, nothing on my list besides the deprecation warnings. But they can be resolved later.

Thanks... yeah 2.x will be way more fun!
