### ISSUE TITLE
Release the 1.1.0.Final

### ISSUE THREAD

**Issue by rhusar** [arquillian/arquillian-extension-warp#231]
Last release for EE 8, next is Jakarta EE 10.

Payload as discussed https://github.com/arquillian/arquillian-extension-warp/issues/213

**Comment by rhusar** [comment]
@WolfgangHG Do you think we can proceed with the current main for release?

**Comment by WolfgangHG** [comment]
Nope, I am done. We can switch to JakartaEE 10.

**Comment by WolfgangHG** [comment]
Just to confirm: I tested 1.0.1.Final and 1.1.0.Final-SNAPSHOT with my small sample project and both work.

**Comment by rhusar** [comment]
Cool! 👽

**Comment by rhusar** [comment]
Done https://github.com/arquillian/arquillian-extension-warp/releases/tag/1.1.0.Final
