### ISSUE TITLE
Tomcat profiles do not run

### ISSUE THREAD

**Issue by WolfgangHG** [arquillian/arquillian-extension-warp#86]
This error occurs e.g. for "tomcat-managed-6":

`
org.jboss.shrinkwrap.resolver.api.NoResolvedResultException: Unable to collect/resolve dependency tree for a resolution due to: Could not find artifact org.richfaces:richfaces-build-resources:zip:configuration-tomcat:${version.richfaces} in central (https://repo1.maven.org/maven2), caused by: Could not find artifact org.richfaces:richfaces-build-resources:zip:configuration-tomcat:${version.richfaces} in central (https://repo1.maven.org/maven2)
`

The property "version.richfaces" is nowhere declared. Richfaces is end of life since 2016, so repairing it makes no sense. But a JSF test using Tomcat might be reasonable. 

Question is: shall tomcat tests be fixed? If yes: what JSF implementation?

Also note: [arquillian-container-tomcat](https://github.com/arquillian/arquillian-container-tomcat) supports currently only embedded containers. Support for remote or managed containers was removed after Tomcat 8. I don't know whether it is possible to add a JSF implementation to an embeddded container.

**Comment by WolfgangHG** [comment]
@chengfang To bring this back: what to do with the tomcat profiles? 

I think it would be best to remove them as:

- RichFaces is no longer maintained and was probably removed from the extension a long time ago (the "version.richfaces" property must have been declared somewhere). So we would need another JSF implementation to install to a manged Tomcat. 
- The required parts of "arquillian-container-tomcat" (remote and managed containers) are discontinued. This would mean major effort to create a working test.
- Finally: there is a profile for TomEE and this one is based on Tomcat.

**Comment by chengfang** [comment]
@WolfgangHG I agree. These are good reasons to remove tomcat profiles.

**Comment by WolfgangHG** [comment]
@chengfang 
Because of the "richfaces" name I stumabled accross those two properties in "ftest-base\pom.xml":
```
    <arquillian.richfaces.servletContainerSetup>false</arquillian.richfaces.servletContainerSetup>
    <arquillian.richfaces.jsfImplementation>org.glassfish:javax.faces</arquillian.richfaces.jsfImplementation>
```

The are used in "build\resources\src\main\resources\arquillian.xml":

```
  <extension qualifier="suite">
    <!-- true if the JSF should be added to the WebArchive for support of plain Servlet containers (Tomcat, Jetty, etc.) -->
    <property name="servletContainerSetup">${arquillian.richfaces.servletContainerSetup}</property>
    <!-- GAV of the JSF implementation used for testing in servlet containers -->
    <property name="jsfImplementation">${arquillian.richfaces.jsfImplementation}</property>
```

..and those are written to "org.arquillian.warp.ftest.configuration.IntegrationTestConfiguration". But as far as I see, those two properties of this class are not used at all, while others are used to install managed containers. Maybe a relict of a long ago removed richfaces support?

Shall I remove all config and code snippets mentioned in this code?

**Comment by chengfang** [comment]
@WolfgangHG I don't know the history behind it. But your plan sounds good to me. I didn't see any other use after a quick search either.

**Comment by WolfgangHG** [comment]
Done by #133
